# CodeRabbit Configuration for Eva Wellbeing Platform
# AI-powered code review configuration

# CodeRabbit Configuration for Eva Wellbeing Platform
reviews:
  auto_review:
    enabled: true
    
  review:
    path_filters:
      - "!node_modules/**"
      - "!dist/**"
      - "!build/**"
      - "!coverage/**"
    
    include_patterns:
      - "**/*.ts"
      - "**/*.tsx" 
      - "**/*.js"
      - "**/*.jsx"
      - "**/*.md"

language:
  typescript:
    type_checking: true
    rules:
      - "prefer-const"
      - "no-unused-vars"
      - "strict-type-checking"

# Medical/Healthcare specific checks
custom_rules:
  healthcare:
    - name: "patient-data-security"
      description: "Check for proper patient data handling"
      severity: "high"
      
    - name: "sensitive-information"
      description: "Flag potential sensitive information exposure"
      severity: "critical"

quality:
  complexity:
    cyclomatic: 10
    cognitive: 15
    
  security:
    enabled: true
    level: "strict"

testing:
  coverage:
    minimum: 70
    critical_functions: 90
    
  critical_areas:
    - "authentication"
    - "patient-data"
    - "symptom-tracking"

ai_focus:
  priority_checks:
    - "security-vulnerabilities"
    - "medical-data-privacy"
    - "accessibility-compliance"

pull_requests:
  auto_assign: true
  require_review: true

compliance:
  hipaa:
    enabled: true
  gdpr:
    enabled: true

performance:
  bundle_size:
    max_size: "500kb"
    warn_size: "300kb"
